
server:
     port: 8001
     
spring:
     application:
              name: querydsl-chapter1        
     datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://127.0.0.1:3306/querydsl?characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
     jpa:
         show-sql: true
           
logging:
    level:
       org:
           hibernate: ERROR
           springframework:
                web: DEBUG
       com:
           chapter1:
                querydsl:
                      service:
                          impl: ERROR
